#!/bin/bash

BIN_NAME="$(basename "$0")"
COMMAND_NAME=$1

sub_help () {
    echo "Usage: $BIN_NAME <command>\n"
    echo "Commands:"
    echo "   all                Install using all options"
    echo "   browsers           Install google chrome and in the future other possible browsers"
    echo "   lando              Install lando and dependencies such as docker and docker-compose"
    echo "   help               This help message"
    echo "   prey               Install Prey - a find my device application for Linux"
    echo "   teams              Install Microsoft Teams"
    echo "   terminus           Install Pantheon Terminus"
    echo "   vscode             Install  VSCode"
}

sub_browsers () {
    sudo chmod +x installers/browsers.bash
    bash installers/browsers.bash
}

sub_lando () {
    sudo chmod +x installers/lando.bash
    bash installers/lando.bash
}

sub_prey () {
    sudo chmod +x installers/prey.bash
    bash installers/prey.bash
}

sub_teams () {
    sudo chmod +x installers/teams.bash
    bash installers/teams.bash
}

sub_terminus () {
    sudo chmod +x installers/terminus.bash
    bash installers/terminus.bash
}

sub_vscode () {
    sudo chmod +x installers/vscode.bash
    bash installers/vscode.bash
}

sub_all () {
    sudo apt update
    sudo apt upgrade
    sub_browsers
    sub_lando
    sub_teams
    sub_terminus
    sub_vscode
    sub_prey
}

case $COMMAND_NAME in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        "sub_${COMMAND_NAME}" "$@"
        if [ $? = 127 ]; then
            echo "'$COMMAND_NAME' is not a known command or has errors." >&2
            sub_help
            exit 1
        fi
        ;;
esac